version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm i
  pre_build:
    commands:
      - npm run test -- --ci --coverage
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "README.md"
